{% set name = "gobject-introspection" %}
{% set major = "1.51" %}
{% set patch = "3" %}
{% set version = major ~ "." ~ patch %}
{% set sha256 = "80acbffd89452b8e30f8a50f46d64517a866ca63157bd1fa78bedb69f9de11c3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ major }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - hugepaths.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - bison
    - cairo 1.14.*
    - flex
    - gettext  # [osx]
    - glib 2.51.*
    - libffi 3.2.*
    - pkg-config  # [not win]
    - python
    - toolchain
  run:
    - glib 2.51.*
    - libffi 3.2.*
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPLv2+
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
