{% set name = "gobject-introspection" %}
{% set version = "1.72.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 02fe8e590861d88f83060dd39cda5ccaa60b2da1d21d0f95499301b186beaabc
  patches:
    - test-fix.patch  # [linux]
    # https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/265
    - pkg-config.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win and vc<14]
  ignore_run_exports:
    # this is only needed to run the full test suite.
    - cairo
    - pixman
    - gettext  # [osx]
    - libffi   # [win]
    - zlib     # [win]
  missing_dso_whitelist:      # [linux]
    - $RPATH/libm.so.6        # [linux]
    - $RPATH/libpthread.so.0  # [linux]
    - $RPATH/libc.so.6        # [linux]
requirements:
  build:
    - python
    - {{ posix }}bison
    - {{ posix }}flex
    - meson >=0.58.2
    - ninja-base
    - pkg-config
    - {{ compiler('c') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ posix }}patch
  host:
    - pkg-config
    - cairo
    - gettext         # [osx]
    - glib >=2.58.0
    - libffi >=3.3
    - pthread-stubs
    - python
    - zlib            # [win]
  run:
    - libffi >=3.3
    - python
    - gettext  # [osx]

test:
  requires:
    - pkg-config
    - conda-build  # [not win]
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - g-ir-scanner --help  # [not win]
    - python "%PREFIX%\\Library\\bin\\g-ir-scanner" --help  # [win]
    - g-ir-compiler --help

    # check that g-ir-scanner can be found through pkg-config (used by downstream builds)
    - test -f `pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`  # [unix]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`) do if not exist "%%a" exit 1  # [win]
  downstreams:
    - pygobject

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: 
    - COPYING
    - COPYING.GPL
    - COPYING.LGPL
  summary: Middleware for binding GObject-based code to other languages.
  description: |
    GObject introspection is a middleware layer between C libraries (using GObject)
    and language bindings. The C library can be scanned at compile time and generate
    a metadata file, in addition to the actual native C library. Then at runtime,
    language bindings can read this metadata and automatically provide bindings to
    call into the C library.
  doc_url: https://gi.readthedocs.io/en/latest/
  dev_url: https://gitlab.gnome.org/GNOME/gobject-introspection/-/tree/main
  doc_source_url: https://gitlab.gnome.org/GNOME/gobject-introspection/-/tree/main/docs

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - scopatz
    - tschoonj
