{% set name = "gobject-introspection" %}
{% set major = "1.53" %}
{% set patch = "5" %}
{% set version = major ~ "." ~ patch %}
{% set sha256 = "b8271d3e3e3044289d06e824605a53b2518593bc2b071db6c90485c837ff437d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/{{ name }}/{{ major }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - hugepaths.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - bison
    - cairo 1.14.*
    - flex
    - gettext  # [osx]
    - pkg-config  # [not win]
    - python
    - pthread-stubs
    - {{ cdt('libx11-devel') }}
    - {{ cdt('libxrender-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libxau-devel') }}
    - {{ cdt('libxext-devel') }}
    - libxcb  # [linux]
  host:
    - glib >=2.53.5,<=3.0a0
    - libffi 3.2.*
    - python
  run:
    - glib >=2.53.5,<=3.0a0
    - libffi 3.2.*
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPLv2+
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
