travis:
  secure:
    BINSTAR_TOKEN: d+5q0sPqOq1l0eUpHwcYEQSbplk1kqcrqXqNJIymPb1r5KgZoatTzzRk+J8D6kK6OxBo2M/UN2x96XAircg/5L6lgEoNSuXQqBW5GFkARtm0vFa73hXJk0DLTK0WGAZBvVkPfc4WRXkzXceqa5jnvTfxEvQuLY6U/A1KrJlNEtdpBBlzL9A3wt/BnYCoplJcEDq97Dt081btodnuBiHzcxvgauAYySWYA/FNjy80cYImjO4JeDRuyVAH6MYQLa4aaICyb9jqyf1bQ9fFD6e0SbwjfU6oA2CfdTPFfYKrtAV1a6DUulAGjt/OCDisWti+bmIipMNLNkVOd1ZoEinIR5K0veSLqk+TCbo2C9bEEl//7hN4CuTGdi14UXNe8FrNoTk/iQ1g4YeMrorM0FhMSPodly17VbvljcIiuradBichL2DWLcNe88zPMWZZFHDkdqqRMmjiGD2w/ZbGCat2aHkluUHYbbFAuNihYdzLhWmx6DXL9Bu/j1QaLHchbs7+swXVg+0uGrtYyK25PsrpoBq0iHOpRjhL/OnRvMZjbW0NIze9mC+0bRLme4h6saHzoR9EZyac7K4FY4uPBKRht8xS/4bh3+JQ6Donzn7LGqHrDa8GymNZdR+yfEQNzzMuz+8tutomZ5SibPPOgl1wJw92LxZ2dHCtfZvPzAAXJEo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
