travis:
  secure:
    BINSTAR_TOKEN: QNrqp3FbR84gAFtbG2BU7JRjiJHR0Ft5VZg+jCtc3TZu+dxMxrMtKFzWP/c3NrTcYC3Gbwc0z4iIchrzXnSyTisiqDjcJvWbt9ZehZt16hzzaOjIHyaIAQUBqmiowIWCA3bApSlh3jnrWTjbjGoakI1BOACaxmrSeNlpH0U9awqu54JcFsNat9FyKAsUoDKiHhOdxXs+vJS2npEcaZ1Exh4G5zKHauZ9K6Ib+3zzM5hjYQH8MNMTkAyzUwOK2q/2KIR9yuT7jnarr/kC7So9Xxh3mw9KZjg09kdMXqvj66c3t7qv0+Mmz/Mkou8rvf/iY1B6AfkI97SrgzagtGkRMk+0Dl1W7iQEQWljRKjfPvGVdIsZtS1UA/UcVwaf7T46U0i/05Kyw68mLuNVNqHzUBqcceplBsA6fvAO8igawqxKVl+a35tIvrQcx74O7iznRN7NXF00dKSAJ3DV7wI+CViYlyUEQJoREAmDQNu6eCg4rMkZcac07HwgLov6pUHf+GocCz85TYYnaUQBdyAyoEyOufj/ZvW+WvdH1vnLQxnDIbqR/zszrVwTpyUtIh1X9OOdCpXcKme//PugwppxuliZZ/4xRf++NWAAJWkQP8wf2YDGzfm3oT9L0XuN1k4UUPgGR5kVH0a9LweVjZtf+2luZgtkgUQzmsCdB68P3Xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
